import { Artwork } from "./types";

const MOCK_SIZES = [
  {
    label: "8 x 12″",
    price: 45,
    formattedPrice: "C$45.00",
    sku: "mock-8x12",
    choices: {
      Size: "8 x 12″",
      FRAME: "No Frame",
      Passepartout: "No border",
    },
    widthCm: 20.32,
    heightCm: 30.48,
  },
  {
    label: "12 x 16″",
    price: 58,
    formattedPrice: "C$58.00",
    sku: "mock-12x16",
    choices: {
      Size: "12 x 16″",
      FRAME: "No Frame",
      Passepartout: "No border",
    },
    widthCm: 30.48,
    heightCm: 40.64,
  },
  {
    label: "18 x 24″",
    price: 68,
    formattedPrice: "C$68.00",
    sku: "mock-18x24",
    choices: {
      Size: "18 x 24″",
      FRAME: "No Frame",
      Passepartout: "No border",
    },
    widthCm: 45.72,
    heightCm: 60.96,
  },
  {
    label: "24 x 36″",
    price: 95,
    formattedPrice: "C$95.00",
    sku: "mock-24x36",
    choices: {
      Size: "24 x 36″",
      FRAME: "No Frame",
      Passepartout: "No border",
    },
    widthCm: 60.96,
    heightCm: 91.44,
  },
];

export const ARTWORKS: Artwork[] = [
  {
    id: "1",
    title: "Ethereal Flow",
    artist: "Elena Rossi",
    price: 450,
    imageUrl: "https://picsum.photos/seed/abstract1/600/800",
    type: "Paper Print",
    width: 150,
    height: 200,
    slug: "ethereal-flow",
    sizes: MOCK_SIZES,
  },
  {
    id: "2",
    title: "Midnight Solace",
    artist: "Marcus Thorne",
    price: 85,
    imageUrl: "https://picsum.photos/seed/abstract2/800/600",
    type: "Paper Print",
    width: 200,
    height: 150,
    slug: "midnight-solace",
    sizes: MOCK_SIZES,
  },
  {
    id: "3",
    title: "Azure Resonance",
    artist: "Sasha Kline",
    price: 120,
    imageUrl: "https://picsum.photos/seed/abstract3/600/600",
    type: "Canvas Print",
    width: 180,
    height: 180,
    slug: "azure-resonance",
    sizes: MOCK_SIZES,
  },
  {
    id: "4",
    title: "Golden Horizon",
    artist: "Elena Rossi",
    price: 520,
    imageUrl: "https://picsum.photos/seed/abstract4/700/500",
    type: "Canvas Print",
    width: 210,
    height: 150,
    slug: "golden-horizon",
    sizes: MOCK_SIZES,
  },
  {
    id: "5",
    title: "Urban Echo",
    artist: "Julian Vane",
    price: 75,
    imageUrl: "https://picsum.photos/seed/abstract5/500/700",
    type: "Paper Print",
    width: 150,
    height: 210,
    slug: "urban-echo",
    sizes: MOCK_SIZES,
  },
  {
    id: "6",
    title: "Verdant Whisper",
    artist: "Sasha Kline",
    price: 110,
    imageUrl: "https://picsum.photos/seed/abstract6/600/800",
    type: "Canvas Print",
    width: 150,
    height: 200,
    slug: "verdant-whisper",
    sizes: MOCK_SIZES,
  },
  {
    id: "7",
    title: "Crimson Tide",
    artist: "Marcus Thorne",
    price: 95,
    imageUrl: "https://picsum.photos/seed/abstract7/800/800",
    type: "Paper Print",
    width: 180,
    height: 180,
    slug: "crimson-tide",
    sizes: MOCK_SIZES,
  },
  {
    id: "8",
    title: "Silent Peak",
    artist: "Elena Rossi",
    price: 380,
    imageUrl: "https://picsum.photos/seed/abstract8/700/900",
    type: "Canvas Print",
    width: 140,
    height: 180,
    slug: "silent-peak",
    sizes: MOCK_SIZES,
  },
  {
    id: "9",
    title: "Neon Pulse",
    artist: "Julian Vane",
    price: 90,
    imageUrl: "https://picsum.photos/seed/abstract9/600/600",
    type: "Paper Print",
    width: 180,
    height: 180,
    slug: "neon-pulse",
    sizes: MOCK_SIZES,
  },
  {
    id: "10",
    title: "Dusty Road",
    artist: "Marcus Thorne",
    price: 130,
    imageUrl: "https://picsum.photos/seed/abstract10/900/600",
    type: "Canvas Print",
    width: 240,
    height: 160,
    slug: "dusty-road",
    sizes: MOCK_SIZES,
  },
  {
    id: "11",
    title: "Woven Light",
    artist: "Sasha Kline",
    price: 410,
    imageUrl: "https://picsum.photos/seed/abstract11/600/900",
    type: "Paper Print",
    width: 160,
    height: 240,
    slug: "woven-light",
    sizes: MOCK_SIZES,
  },
  {
    id: "12",
    title: "Fractal Echo",
    artist: "Elena Rossi",
    price: 80,
    imageUrl: "https://picsum.photos/seed/abstract12/800/800",
    type: "Paper Print",
    width: 200,
    height: 200,
    slug: "fractal-echo",
    sizes: MOCK_SIZES,
  },
];
